### PR TITLE
fix: lifo behaviour for unique mode is not consistent

### PR DESCRIPTION
**Pull request by JBustin**
## Context

For lifo, unique mode

## Actual behaviour

When the batch is greater than the length of the list, the set and the list are out of sync.

## Expected behaviour

We should always have the same count of elements in the list and the set.

## How to reproduce

Run this (`node ./tmp/test.js`) : 

```
const taskman = require('../index');
const { formatList, formatSet } = require('../lib/keys/queue');
const { createClient } = require('../lib/redis');

const NAME = 'taskman_test';
const unique = true;
const redis = { host: 'redis-huit.local' };
const batch = 100;
const sleep = 2000;
const type = 'lifo';
const QUEUED_MS = 1000;
const QUEUED_BATCH = 30;
const MIN = 50;
const MAX = 2000;

const redisCli = createClient(redis);

const list = formatList(NAME);
const set = formatSet(NAME);

redisCli.del(list);
redisCli.del(set);

const worker = taskman.createWorker(NAME, {
  unique,
  redis,
  type,
  batch,
  sleep,
});

const queue = taskman.createQueue(NAME, { unique, redis });

const getRandomInt = () => Math.floor(Math.random() * (MAX - MIN)) + MIN;

process.on('exit', code => {
  console.log('End', code);
  clearInterval(watchInterval);
  queue.close(qErr => {
    if (err) console.error(err);
    if (qErr) console.error(qErr);
    process.exit(0);
  });
});

worker.process((task, done) => {
  console.log('Processed tasks', task.length);
  done();
});

worker.on('job failure', console.log.bind(console, 'job failure'));
worker.on('error', console.log.bind(console, 'error'));
// worker.on('job complete', console.log.bind(console, 'job complete'));
// worker.on('status change', console.log.bind(console, 'status change'));

const watchInterval = setInterval(() => {
  // redisCli.llen(list, console.log.bind(console, `llen ${list}`));
  // redisCli.scard(set, console.log.bind(console, `scard ${set}`));
  const multi = redisCli.multi();
  multi
    .llen(list)
    .scard(set)
    .exec((err, [nbList, nbSet]) => {
      if (err) console.error(err);
      else if (nbSet > nbList) console.log(nbList, nbSet);
    });
}, QUEUED_MS);

const queued = index => {
  for (let i = index; i < index + QUEUED_BATCH; i++) {
    queue.push({ date: Date.now(), index: i, action: 'to_create' });
  }
  setTimeout(() => queued(index++), getRandomInt());
};

setTimeout(() => queued(0), getRandomInt());
```

Without fix : 
```
Processed tasks 100
30 110
60 140
Processed tasks 100
30 130
60 160
Processed tasks 100
0 120
30 150
Processed tasks 100
0 120
30 150
...
```

With fix (and improvement) : 
```
Processed tasks 60
Processed tasks 30
Processed tasks 30
Processed tasks 60
...
```

### CODE REVIEW

**Comment by JBustin** [comment]
The line of the fix : 
https://github.com/neoziro/node-taskman/pull/28/files#diff-b68fbb0f945cdf9cddec65ddf0fbe456R247

**Comment by JBustin** [comment]
@neoziro could you publish the release on npm pliz 
Thx

**Comment by neoziro** [comment]
Yes of course, after DotJS ;)

**Comment by neoziro** [comment]
@JBustin published, also added `.npmignore`:



Before:

```
npm notice name:          node-taskman
npm notice version:       2.1.0
npm notice package size:  42.8 kB
npm notice unpacked size: 137.0 kB
```

After:

```
npm notice name:          node-taskman
npm notice version:       2.1.1
npm notice package size:  7.1 kB
npm notice unpacked size: 25.6 kB
```

**Pull request merged**
